name: build

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pixelkiri/devkitpro-alpine-switch:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: |
          make -j2
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build.zip
          path: |
            build/subsdk9
            build/subsdk9.nss
            build/subsdk9.npdm
      - name: Make a release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Automated Release
          draft: false
          prerelease: false
          files: build.zip