name: build

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pixelkiri/devkitpro-alpine-switch:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build
        run: |
          make -j2
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            build/subsdk9
            build/subsdk9.nss
            build/subsdk9.npdm
